Repository linkerd/linkerd2, pull requests merged in 2018-07, with the labels that each got.

#1243 proxy: Always inlcude `tls` label in metrics
  proxy/src/ctx/transport.rs
  proxy/src/telemetry/metrics/labels.rs
  proxy/src/telemetry/metrics/record.rs
  proxy/tests/telemetry.rs
Labels: area/proxy

#1247 Change CLI and web TLS indicators from Secured to TLS
  cli/cmd/stat.go
  cli/cmd/stat_test.go
  test/stat/stat_test.go
  web/app/js/components/MetricsTable.jsx
Labels: area/cli, area/web

#1237 Add more tests for the stat summary endpoint --from flags
  controller/api/public/stat_summary_test.go
Labels: area/controller

#1256 proxy: Handle connection close during TLS detection
  proxy/src/connection.rs
Labels: area/proxy

#1246 Small tweaks to error modal, add Reason to api error response
  controller/api/public/stat_summary.go
  controller/gen/public/public.pb.go
  proto/public.proto
  web/app/css/service-mesh.css
  web/app/js/components/ErrorModal.jsx
  web/app/js/components/ServiceMesh.jsx
Labels: area/controller, area/web

#1263 proxy: Fix out-of-control inotify CPU use
  Cargo.lock
  proxy/Cargo.toml
Labels: area/proxy

#1180 doc update to remove extra configurations for websockets
  README.md
  doc/adding-your-service.md
Labels: area/docs

#1268 Document Conduit's Automatic TLS feature
  doc/automatic-tls.md
Labels: area/docs, area/tls

#1260 Start removing references to conduit in the web UI
  web/app/css/conduit-spinner.css
  web/app/css/service-mesh.css
  web/app/css/styles.css
  web/app/js/components/ConduitSpinner.jsx
  web/app/js/components/ErrorModal.jsx
  web/app/js/components/GrafanaLink.jsx
  web/app/js/components/MetricsTable.jsx
  web/app/js/components/Namespace.jsx
  web/app/js/components/PageHeader.jsx
  web/app/js/components/ResourceList.jsx
  web/app/js/components/ServiceMesh.jsx
  web/app/js/components/Sidebar.jsx
  web/app/js/components/StatusTable.jsx
  web/app/js/components/Version.jsx
  web/app/js/components/util/ApiHelpers.jsx
  web/app/js/index.js
  web/app/test/ApiHelpersTest.jsx
  web/app/test/GrafanaLinkTest.jsx
  web/app/test/ResourceListTest.jsx
  web/app/test/ServiceMeshTest.jsx
  web/app/test/fixtures/podRollup.json
  web/app/test/testHelpers.jsx
Labels: area/web

#1204 proxy: Add tls_config_last_reload_seconds metric
  proxy/src/telemetry/event.rs
  proxy/src/telemetry/metrics/labels/mod.rs
  proxy/src/telemetry/metrics/mod.rs
  proxy/src/telemetry/metrics/record.rs
  proxy/src/telemetry/sensor/mod.rs
Labels: area/proxy, area/telemetry, priority/P1

#1289 Fix authority stat queries when a --from flag is used
  controller/api/public/stat_summary.go
  controller/api/public/stat_summary_test.go
Labels: area/cli

#1297 Update for current CLI
  BUILD.md
Labels: bug

#1300 docker: Ensure that TLS is validated when fetching the proxy
  Dockerfile-proxy
Labels: area/build

#1295 Name ClusterRole objects to be namespace-specific
  bin/test-run
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: area/cli, area/controller, area/production

#1290 Continue to remove conduit branding from /web
  web/app/css/sidebar.css
  web/app/css/styles.css
  web/app/js/components/ServiceMesh.jsx
  web/app/test/ServiceMeshTest.jsx
  web/app/test/fixtures/allRollup.json
  web/app/test/fixtures/namespaces.json
  web/app/test/fixtures/podRollup.json
  web/app/test/testHelpers.jsx
Labels: area/web

#1305 Fix annoying flickering if image asset isn't present
  web/app/css/sidebar.css
Labels: area/web

#1321 Add flag that skips `dep ensure` to bin/fast-build
  bin/fast-build
Labels: area/build

#1320 update grafana dashboards: conduit -> linkerd
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
  grafana/dashboards/deployment.json
  grafana/dashboards/health.json
  grafana/dashboards/pod.json
  grafana/dashboards/replication-controller.json
  grafana/dashboards/service.json
  grafana/dashboards/top-line.json
  web/app/js/components/GrafanaLink.jsx
  web/app/test/GrafanaLinkTest.jsx
Labels: area/web

#1328 Update readme to reference linkerd2
  README.md
Labels: area/docs

#1331 Update docs to reference Linkerd
  CONTRIBUTING.md
  README.md
  doc/README.md
  doc/adding-your-service.md
  doc/automatic-tls.md
  doc/debugging-an-app.md
  doc/get-involved.md
  doc/getting-started.md
  doc/images/dashboard.png
  doc/overview.md
  doc/prometheus.md
  doc/proxy-metrics.md
Labels: area/docs

#1355 Update prometheus labels to match k8s resource names
  cli/cmd/get.go
  cli/cmd/stat.go
  cli/cmd/stat_test.go
  cli/cmd/tap_test.go
  cli/cmd/testdata/inject_emojivoto_statefulset.golden.yml
  controller/api/public/stat_summary.go
  controller/api/public/stat_summary_test.go
  controller/api/util/api_utils.go
  controller/api/util/api_utils_test.go
  controller/ca/controller.go
  controller/destination/listener.go
  controller/destination/listener_test.go
  controller/k8s/api.go
  controller/k8s/api_test.go
  controller/tap/server.go
  controller/tap/server_test.go
  doc/proxy-metrics.md
  grafana/dashboards/replicationcontroller.json
  pkg/k8s/k8s.go
  pkg/k8s/k8s_test.go
  pkg/k8s/labels.go
  pkg/k8s/labels_test.go
  web/app/js/components/ErrorModal.jsx
  web/app/js/components/GrafanaLink.jsx
  web/app/js/components/MetricsTable.jsx
  web/app/js/components/Namespace.jsx
  web/app/js/components/ResourceList.jsx
  web/app/js/components/util/ApiHelpers.jsx
  web/app/js/components/util/Utils.js
  web/app/js/index.js
  web/app/test/GrafanaLinkTest.jsx
  web/app/test/MetricUtilsTest.js
  web/app/test/ResourceListTest.jsx
  web/app/test/ServiceMeshTest.jsx
  web/app/test/fixtures/allRollup.json
  web/app/test/fixtures/deployRollup.json
  web/app/test/fixtures/emojivotoPods.json
  web/app/test/fixtures/multiDeployRollup.json
  web/app/test/fixtures/namespaces.json
  web/app/test/fixtures/podRollup.json
  web/srv/api_handlers.go
Labels: review

#1356 Enable Tap from the Web UI
  Gopkg.lock
  Gopkg.toml
  cli/Dockerfile-bin
  cli/cmd/tap.go
  cli/cmd/tap_test.go
  controller/Dockerfile
  controller/api/util/api_utils.go
  proxy-init/Dockerfile
  web/Dockerfile
  web/app/css/tap.css
  web/app/js/components/Sidebar.jsx
  web/app/js/components/Tap.jsx
  web/app/js/index.js
  web/srv/api_handlers.go
  web/srv/server.go
Labels: area/controller, area/web, review, reviewable

#1365 Build version tags in CI
  .travis.yml
  bin/_tag.sh
Labels: review, reviewable

#1367 Send glog logs to stderr by default
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
  controller/cmd/ca/main.go
  controller/cmd/destination/main.go
  controller/cmd/proxy-api/main.go
  controller/cmd/public-api/main.go
  controller/cmd/tap/main.go
  pkg/flags/flags.go
  pkg/version/version.go
  web/main.go
Labels: review, reviewable

#1338 Don't relink web & controller executables when version changes.
  controller/Dockerfile
  pkg/version/version.go
  web/Dockerfile
Labels: area/build

#1372 Fix build on Linux.
  bin/_tag.sh
Labels: area/build, review, reviewable

#1339 bin/test-cleanup: Delete test namespaces in paralllel.
  bin/test-cleanup
Labels: area/test

#1369 Update k8s.io dependencies to 1.11.1
  Gopkg.lock
  Gopkg.toml
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  web/Dockerfile
Labels: review, reviewable

#1375 Update location of emojivoto kubernetes config
  BUILD.md
  doc/getting-started.md
Labels: review, reviewable

#1383 fixup deps
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  web/Dockerfile
Labels: review, reviewable

#1381 Remove remaining conduit references in codebase
  BUILD.md
  CONTRIBUTING.md
  README.md
  cli/cmd/check.go
  web/app/js/components/Sidebar.jsx
  web/app/js/components/SocialLinks.jsx
  web/app/js/components/Version.jsx
Labels: review

#1371 Add more filters to the web UI tap form
  controller/api/public/grpc_server.go
  web/app/css/tap.css
  web/app/js/components/ErrorBanner.jsx
  web/app/js/components/Sidebar.jsx
  web/app/js/components/Tap.jsx
  web/app/package.json
  web/app/yarn.lock
Labels: area/web, review, reviewable

#1382 Bump install timeout in integration tests
  test/install_test.go
Labels: review, reviewable

#1388 Add script to extract binaries from prebuilt cli-bin image
  bin/docker-pull-binaries
Labels: review, reviewable

#1389 Update CHANGES.md for v18.7.3 release
  CHANGES.md
Labels: review, reviewable
