Repository linkerd/linkerd2, pull requests merged in 2018-02, with the labels that each got.

#298 Optimize Prometheus queries
  Gopkg.lock
  Gopkg.toml
  cli/Dockerfile-bin
  controller/Dockerfile
  controller/api/public/grpc_server.go
  controller/api/public/grpc_server_test.go
  controller/telemetry/server.go
  controller/telemetry/server_test.go
  proxy-init/Dockerfile
  web/Dockerfile
Labels: controller, review

#315 Remove per-path metrics from UIs
  cli/cmd/stat.go
  web/app/js/components/DeploymentDetail.jsx
  web/app/js/components/Paths.jsx
  web/app/js/index.js
Labels: cli, review, web

#320 Remove per-pod metrics aggregation
  controller/api/public/grpc_server.go
  controller/api/util/api_utils.go
  controller/api/util/api_utils_test.go
  controller/gen/public/api.pb.go
  proto/public/api.proto
Labels: review

#317 Remove per-path metrics from telemetry pipeline
  cli/cmd/stat.go
  controller/api/public/grpc_server.go
  controller/api/public/grpc_server_test.go
  controller/api/public/http_server_test.go
  controller/api/public/proto_over_http_test.go
  controller/api/util/api_utils.go
  controller/api/util/api_utils_test.go
  controller/gen/proxy/telemetry/telemetry.pb.go
  controller/gen/public/api.pb.go
  controller/script/simulate-proxy/main.go
  controller/telemetry/server.go
  proto/proxy/telemetry/telemetry.proto
  proto/public/api.proto
  proxy/src/telemetry/metrics/mod.rs
  proxy/tests/telemetry.rs
  web/srv/api_handlers.go
Labels: review

#323 Concurrent Telemetry requests
  controller/api/public/grpc_server.go
Labels: controller, review

#330 Fix pointer copying
  controller/api/public/grpc_server.go
  controller/api/public/grpc_server_test.go
Labels: bug, review

#321 Clean up DeploymentList page
  web/app/js/components/DeploymentsList.jsx
Labels: review, web

#319 UI updates, graph removals
  web/app/css/health-pane.css
  web/app/css/metric-summary.css
  web/app/css/sidebar.css
  web/app/js/components/DeploymentDetail.jsx
  web/app/js/components/DeploymentsList.jsx
  web/app/js/components/MetricsSummary.jsx
  web/app/js/components/Routes.jsx
  web/app/js/components/ServiceMesh.jsx
  web/app/js/components/Sidebar.jsx
  web/app/js/components/SocialLinks.jsx
  web/app/js/components/UpstreamDownstream.jsx
  web/app/js/index.js
Labels: review, web

#324 Use bin/dep in Dockerfile-go-deps.
  .dockerignore
  Dockerfile-go-deps
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  web/Dockerfile
Labels: review

#325 Improve the caching behavior of Dockerfile-go-deps.
  Dockerfile-go-deps
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  web/Dockerfile
Labels: review

#326 Upgrade to Go 1.9.4.
  Dockerfile-go-deps
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  proxy-init/integration_test/iptables/Dockerfile-tester
  web/Dockerfile
Labels: review

#344 Upgrade to Prometheus 2.1.0
  cli/cmd/install.go
  cli/cmd/testdata/install_output.golden
  docker-compose.yml
Labels: review

#332 Precompile large Go libraries in go-deps Docker image.
  Dockerfile-go-deps
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  web/Dockerfile
Labels: review

#288 Improve wording around Getting Started
  README.md
Labels: review

#342 Require timestamp on all telemetry requests
  controller/api/public/grpc_server.go
  controller/api/public/grpc_server_test.go
  controller/telemetry/server.go
  controller/telemetry/server_test.go
  proto/controller/telemetry/telemetry.proto
Labels: bug, review

#327 Test the proxy in release mode in Docker in CI on the master branch.
  .travis.yml
Labels: review

#348 Ensure latency quantile queries match timestamps
  controller/api/public/grpc_server.go
  controller/api/public/grpc_server_test.go
Labels: bug, review

#356 Remove unused web routes and helper
  web/app/js/components/util/ApiHelpers.jsx
  web/srv/server.go
Labels: review, web

#338 Use Prometheus to track added data plane pods.
  controller/telemetry/server.go
Labels: review

#367 Strip `conduit` CLI executables in `docker build`.
  cli/Dockerfile-bin
Labels: review

#371 B/inject proxy into control plane
  cli/cmd/inject_test.go
  cli/cmd/install.go
  cli/cmd/install_test.go
  cli/cmd/testdata/inject_emojivoto_deployment.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment.input.yml
  cli/cmd/testdata/install_output.golden
  cli/cmd/testdata/render_install_output.golden
Labels: review

#363 Upgrade to Rust 1.24.0
  BUILD.md
  proxy/Dockerfile
Labels: review

#379 Refactor `conduit inject` code to make it unit-testable.
  cli/cmd/inject.go
  cli/cmd/inject_test.go
  cli/cmd/install_test.go
  cli/cmd/test_helper.go
  cli/cmd/testdata/inject_emojivoto_deployment.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment.input.yml
Labels: review

#380 Skip pods with hostNetwork=true in `conduit inject`
  cli/cmd/inject.go
  cli/cmd/inject_test.go
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_false.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_false.input.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_true.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_true.input.yml
Labels: review

#289 add check and friendly error if conduit dashboard is not installed
  cli/cmd/dashboard.go
  cli/cmd/dashboard_test.go
Labels: review

#382 CLI: Remove now-unnecessary "enhanced" Kubernetes object types
  cli/cmd/inject.go
Labels: review

#383 Refactor `conduit inject` code to eliminate duplicate logic
  cli/cmd/inject.go
Labels: review

#377 Small UI tweaks for 0.3 prep
  web/app/js/components/DeploymentDetail.jsx
  web/app/js/components/DeploymentsList.jsx
  web/app/js/components/MetricsTable.jsx
  web/app/js/components/ServiceMesh.jsx
  web/app/js/components/StatusTable.jsx
  web/app/js/components/util/MetricUtils.js
  web/app/js/components/util/Utils.js
  web/app/test/ServiceMeshTest.jsx
  web/app/test/UtilsTest.js
Labels: review, web

#391 update readme: experimental -> alpha, and minor tweaks
  README.md
Labels: review

#374 Add ability to cancel promises via a wrapper
  web/app/js/components/DeploymentDetail.jsx
  web/app/js/components/DeploymentsList.jsx
  web/app/js/components/ServiceMesh.jsx
  web/app/js/components/Sidebar.jsx
  web/app/js/components/Version.jsx
  web/app/js/components/util/ApiHelpers.jsx
  web/app/test/ApiHelpersTest.jsx
Labels: review, web

#395 Add some space between the sidebar collapse button and headings
  web/app/css/styles.css
Labels: review, trivial, web

#394 Run conduit dashboard on ephemeral port by default
  cli/cmd/dashboard.go
Labels: review

#389 Print error message only when invalid YAML file is used with inject command
  cli/cmd/inject.go
  cli/cmd/inject_test.go
  cli/cmd/test_helper.go
  cli/cmd/testdata/inject_gettest_deployment.bad.golden
  cli/cmd/testdata/inject_gettest_deployment.bad.input.yml
  cli/cmd/testdata/inject_gettest_deployment.good.golden.yml
  cli/cmd/testdata/inject_gettest_deployment.good.input.yml
Labels: review

#393 Update go-run to set version equal to root-tag
  bin/go-run
  cli/cmd/inject.go
  cli/cmd/inject_test.go
  cli/cmd/testdata/inject_emojivoto_deployment.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_false.golden.yml
  cli/cmd/testdata/inject_gettest_deployment.good.golden.yml
  pkg/version/version.go
Labels: review

#400 Remove uses of upstream/downstream from web UI
  web/app/js/components/ResourceHealthOverview.jsx
  web/app/js/components/UpstreamDownstream.jsx
Labels: review

#397 proxy: use original dst if authority doesnt look like local service
  proxy/src/config.rs
  proxy/src/fully_qualified_authority.rs
  proxy/src/outbound.rs
  proxy/tests/discovery.rs
  proxy/tests/support/proxy.rs
  proxy/tests/telemetry.rs
  proxy/tests/transparency.rs
Labels: review

#401 Improve get/stat/tap help text by way of examples
  cli/cmd/get.go
  cli/cmd/stat.go
  cli/cmd/tap.go
Labels: review

#398 Limit the max number of in-flight requests in proxy.
  Cargo.lock
  proxy/Cargo.toml
  proxy/src/inbound.rs
  proxy/src/lib.rs
  proxy/src/outbound.rs
Labels: review

#406 Prepare for the v0.3.0 release
  CHANGES.md
  Cargo.lock
  proxy/Cargo.toml
  proxy/controller-grpc/Cargo.toml
  proxy/convert/Cargo.toml
  proxy/futures-mpsc-lossy/Cargo.toml
  proxy/router/Cargo.toml
Labels: review

#407 Remove temporary files generated by dep in go-deps image.
  Dockerfile-go-deps
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  web/Dockerfile
Labels: review

#399 Remove timestamps from log messages
  Cargo.lock
  proxy/Cargo.toml
  proxy/src/lib.rs
  proxy/src/logging.rs
Labels: enhancement, proxy, review

#408 Use Go 1.10.0 to build Go components.
  .travis.yml
  Dockerfile-go-deps
  Gopkg.lock
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  proxy-init/integration_test/iptables/Dockerfile-tester
  web/Dockerfile
Labels: review

#411 proxy: add more tests for loopback IPs in FullyQualifiedAuthority
  proxy/src/fully_qualified_authority.rs
Labels: review

#424 proxy: improve overall quality of logs
  proxy/src/control/discovery.rs
  proxy/src/control/mod.rs
  proxy/src/control/telemetry.rs
  proxy/src/logging.rs
  proxy/src/timeout.rs
  proxy/src/transport/so_original_dst.rs
Labels: review

#409 Make build scripts location-agnostic
  BUILD.md
  bin/_docker.sh
  bin/_gcp.sh
  bin/_log.sh
  bin/_tag.sh
  bin/conduit
  bin/docker-build
  bin/docker-build-base
  bin/docker-build-cli
  bin/docker-build-cli-bin
  bin/docker-build-controller
  bin/docker-build-go-deps
  bin/docker-build-proxy
  bin/docker-build-proxy-init
  bin/docker-build-web
  bin/docker-images
  bin/docker-pull
  bin/docker-pull-deps
  bin/docker-push
  bin/docker-push-deps
  bin/docker-retag-all
  bin/go-run
  bin/mkube
  bin/protoc
  bin/root-tag
  bin/update-go-deps-shas
Labels: review

#427 proxy: fix intermittent tap match method quickcheck failure
  proxy/src/telemetry/tap/match_.rs
Labels: review

#365 Inject the conduit proxy into controller pod during conduit install
  cli/cmd/inject.go
  cli/cmd/inject_test.go
  cli/cmd/install.go
  cli/cmd/install_test.go
  cli/cmd/testdata/inject_emojivoto_deployment_controller_name.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_controller_name.input.yml
  cli/cmd/testdata/install_output.golden
Labels: review

#423 Move install template to its own file
  cli/cmd/install.go
  cli/install/template.go
Labels: review

#373 Remove redundant `app` labels in control plane.
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: review

#368 Base control plane Docker images on scratch instead of base.
  cli/Dockerfile-bin
  controller/Dockerfile
Labels: review

#376 Add a test of the actual default output of `conduit install`.
  cli/cmd/install.go
  cli/cmd/install_test.go
  cli/cmd/testdata/install_default.golden
Labels: review

#410 proxy: don't send transfer-encoding for empty GET requests
  Cargo.lock
  proxy/Cargo.toml
  proxy/src/transparency/glue.rs
  proxy/tests/transparency.rs
Labels: review

#441 Add flaky_tests feature for skipping some tests on CI
  proxy/Cargo.toml
  proxy/Dockerfile
  proxy/tests/telemetry.rs
Labels: build, proxy, review

#450 Stop using the url crate in the proxy.
  Cargo.lock
  proxy/Cargo.toml
  proxy/src/config.rs
  proxy/src/control/mod.rs
  proxy/src/dns.rs
  proxy/src/lib.rs
  proxy/src/transport/connect.rs
  proxy/src/transport/mod.rs
  proxy/tests/support/mod.rs
Labels: build, review

#451 Remove the unused tokio-proto build dependency.
  Cargo.lock
  proxy/Cargo.toml
Labels: build, review

#465 Turn off the `use_logging` default feature of quickcheck.
  Cargo.lock
  proxy/Cargo.toml
  proxy/controller-grpc/Cargo.toml
Labels: review

#445 Upgrade to env_logger 0.5 & turn off its regex feature
  Cargo.lock
  proxy/Cargo.toml
  proxy/src/logging.rs
  proxy/tests/discovery.rs
  proxy/tests/telemetry.rs
  proxy/tests/transparency.rs
Labels: build, review

#471 Fix intermittent outbound_times_out failure.
  proxy/tests/discovery.rs
Labels: review

#466 Proxy: Upgrade from ordermap 0.2 crate to indexmap 0.4.
  Cargo.lock
  proxy/Cargo.toml
  proxy/router/Cargo.toml
  proxy/router/src/lib.rs
  proxy/src/control/observe.rs
  proxy/src/lib.rs
  proxy/src/telemetry/metrics/mod.rs
  proxy/src/telemetry/tap/mod.rs
Labels: build, review

#468 Update abstract-ns and tempdir dependencies to use rand 0.4.
  Cargo.lock
Labels: review

#474 Skip flaky tests in non-Docker CI builds
  .travis.yml
Labels: build, review, trivial

#459 Ensure tap requests at least 1rps from each pod
  controller/tap/server.go
Labels: review

#460 cli: add check for latest version of cli and control plane
  cli/cmd/check.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: cli, enhancement, usability

#476 Refactor FullyQualifiedAuthority::normalize to always return authority
  proxy/src/control/discovery.rs
  proxy/src/fully_qualified_authority.rs
  proxy/src/outbound.rs
Labels: proxy, refactoring, review

#444 Add Grafana to conduit install
  BUILD.md
  cli/cmd/install.go
  cli/cmd/install_test.go
  cli/cmd/test_helper.go
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/health.go
  cli/install/template.go
  cli/install/viz.go
Labels: P1, controller, review

#482 cli: refactor k8s config to support $KUBECONFIG with multiple paths
  cli/cmd/check.go
  cli/cmd/dashboard.go
  cli/cmd/root.go
  pkg/k8s/api.go
  pkg/k8s/api_test.go
  pkg/k8s/k8s.go
  pkg/k8s/k8s_test.go
  pkg/k8s/proxy.go
  pkg/k8s/proxy_test.go
  pkg/shell/shell.go
  pkg/shell/shell_test.go
  pkg/shell/test_helper.go
Labels: cli, enhancement, k8s

#472 proxy: de-duplicate method parsing in tap quickcheck
  proxy/src/telemetry/tap/match_.rs
Labels: review

#418 Move Conduit documentation sources to Conduit repo.
  doc/README.md
  doc/adding-your-service.md
  doc/debugging-an-app.md
  doc/get-involved.md
  doc/getting-started.md
  doc/images/dashboard-data-plane.png
  doc/images/dashboard.png
  doc/images/emojivoto-poop.png
  doc/overview.md
  doc/prometheus.md
  doc/roadmap.md
Labels: review
