Repository linkerd/linkerd2, pull requests merged in 2018-03, with the labels that each got.

#464 Add DNS label validation in destination service
  controller/destination/server.go
  controller/destination/server_test.go
Labels: review

#495 Proxy: Update domain dep. to remove rand 0.3 dep.
  Cargo.lock
  proxy/Cargo.toml
Labels: review

#463 proxy: detect TCP socket hang ups from client or server
  proxy/src/connection.rs
  proxy/src/transparency/tcp.rs
  proxy/tests/support/tcp.rs
  proxy/tests/transparency.rs
Labels: P0, review

#490 Handle ExternalName-type svcs in destination service
  controller/destination/dns.go
  controller/destination/dns_test.go
  controller/destination/server.go
  controller/destination/server_test.go
  controller/k8s/endpoints.go
  controller/util/util.go
Labels: review

#477 Use fmt::Display to format error messages in logs
  proxy/router/src/lib.rs
  proxy/src/bind.rs
  proxy/src/inbound.rs
  proxy/src/lib.rs
  proxy/src/map_err.rs
  proxy/src/outbound.rs
Labels: enhancement, proxy, review

#509 Install: Don't install buoyantio/kubectl into the prometheus pod.
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: review

#487 Remove connect timeouts from Bind
  proxy/src/bind.rs
  proxy/src/config.rs
  proxy/src/lib.rs
  proxy/src/transport/connect.rs
  proxy/src/transport/mod.rs
Labels: needs signoff, proxy, review

#513 Remove mention of Grafana from BUILD.md
  BUILD.md
Labels: review

#516 Fix flakey dns_test
  controller/destination/dns_test.go
Labels: review

#493 Exclude telemetry generated by the control plane when requesting depl…
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
  controller/api/public/grpc_server.go
  controller/api/public/grpc_server_test.go
  controller/api/public/http_server.go
  controller/cmd/public-api/main.go
Labels: review

#457 proxy: preserve body headers in http1
  Cargo.lock
  proxy/Cargo.toml
  proxy/src/transparency/client.rs
  proxy/src/transparency/glue.rs
  proxy/tests/support/client.rs
  proxy/tests/support/mod.rs
  proxy/tests/transparency.rs
Labels: P0, review

#514 Refactor `ReconstructUri` into a `Service` inside of `Bind`
  proxy/src/bind.rs
  proxy/src/transparency/glue.rs
  proxy/src/transparency/h1.rs
Labels: review

#497 Add --expected-version flag for conduit check command
  BUILD.md
  cli/cmd/check.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: review

#506 Update prost to 0.3.2 to remove 29 crate dependencies.
  Cargo.lock
Labels: review

#521 Disable Grafana update check
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: review

#492 Enforce that requests are mapped to connections for each Host: header values
  Cargo.lock
  proxy/Cargo.toml
  proxy/router/src/lib.rs
  proxy/src/bind.rs
  proxy/src/inbound.rs
  proxy/src/outbound.rs
  proxy/src/transparency/client.rs
  proxy/src/transparency/glue.rs
  proxy/src/transparency/h1.rs
  proxy/src/transparency/mod.rs
  proxy/tests/support/proxy.rs
  proxy/tests/support/server.rs
  proxy/tests/support/tcp.rs
  proxy/tests/transparency.rs
Labels: proxy, review, security

#524 Set -logtostderr flag on controller components
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: review

#525 Make absolute names truly absolute.
  cli/cmd/inject.go
  cli/cmd/testdata/inject_emojivoto_deployment.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_controller_name.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_false.golden.yml
  cli/cmd/testdata/inject_gettest_deployment.good.golden.yml
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: review

#526 Patch prost-derive 0.3.2 to current master to prune dependencies.
  Cargo.lock
  Cargo.toml
Labels: review

#533 Revert "Make absolute names truly absolute. (#525)"
  cli/cmd/inject.go
  cli/cmd/testdata/inject_emojivoto_deployment.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_controller_name.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_false.golden.yml
  cli/cmd/testdata/inject_gettest_deployment.good.golden.yml
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: review

#527 Proxy: Make CONDUIT_PROXY_POD_NAMESPACE a required parameter.
  proxy/src/config.rs
  proxy/src/ctx/mod.rs
Labels: review

#510 Retry k8s watch endpoints on error
  Gopkg.lock
  cli/Dockerfile-bin
  controller/Dockerfile
  controller/k8s/endpoints.go
  controller/k8s/pods.go
  controller/k8s/replicasets.go
  controller/k8s/watcher.go
  controller/k8s/watcher_test.go
  proxy-init/Dockerfile
  web/Dockerfile
Labels: review

#537 Fix infinite loop in `tcp::HalfDuplex::copy_into()`
  proxy/src/transparency/tcp.rs
Labels: proxy, review

#539 Proxy: Update h2 dependency.
  Cargo.lock
Labels: review

#535 proxy: improve transparency of host headers and absolute-uris
  Cargo.lock
  proxy/Cargo.toml
  proxy/src/bind.rs
  proxy/src/transparency/client.rs
  proxy/src/transparency/h1.rs
  proxy/tests/transparency.rs
Labels: review

#550 Proxy: Update deps to improve logging and remove slab 0.3 & ordermap deps
  Cargo.lock
Labels: review

#555 Fix outbound HTTP/1 requests not using Destinations
  proxy/src/outbound.rs
  proxy/src/transparency/h1.rs
  proxy/tests/discovery.rs
Labels: proxy, review

#556 Run all discovery tests for HTTP/1 as well as HTTP/2
  proxy/tests/discovery.rs
Labels: review

#494 Most controller listeners should only bind on localhost
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
  controller/cmd/destination/main.go
  controller/cmd/proxy-api/main.go
  controller/cmd/public-api/main.go
  controller/cmd/tap/main.go
  controller/cmd/telemetry/main.go
Labels: review

#551 Stop collapsing Cargo.lock in GitHub PR reviews.
  .gitattributes
Labels: review

#572 Proxy: Bump h2 to 0.1.2
  Cargo.lock
  proxy/Cargo.toml
  proxy/router/Cargo.toml
Labels: review

#574 Update release notes for v0.3.1.
  CHANGES.md
Labels: review

#579 Remove the cli docker image.
  bin/docker-build
  bin/docker-build-cli
  cli/Dockerfile
Labels: review

#581 proxy: add SIGTERM and SIGQUIT handlers
  Cargo.lock
  proxy/Cargo.toml
  proxy/src/lib.rs
  proxy/src/main.rs
  proxy/src/signal.rs
  proxy/tests/support/proxy.rs
Labels: review

#536 Add proxy metrics documentation
  doc/proxy-metrics.md
Labels: priority/P0, review

#590 Add Grafana support to conduit dashboard command
  cli/cmd/dashboard.go
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: area/cli, area/telemetry, review

#594 Update codegen and tower-balance to remove indexmap dep.
  Cargo.lock
Labels: review

#593 Avoid `cargo fetch --locked` in proxy/Dockerfile.
  proxy/Dockerfile
Labels: review

#596 Update tempdir dependency to improve deps situation.
  Cargo.lock
Labels: area/build, review

#597 Proxy: Download fewer crates in Travis CI runs
  .travis.yml
Labels: review

#569 Add response duration and latency histograms to proxy metrics
  proxy/src/config.rs
  proxy/src/lib.rs
  proxy/src/telemetry/control.rs
  proxy/src/telemetry/metrics/latency.rs
  proxy/src/telemetry/metrics/mod.rs
  proxy/src/telemetry/metrics/prometheus.rs
  proxy/tests/support/proxy.rs
  proxy/tests/telemetry.rs
Labels: area/proxy, area/telemetry, review

#576 Modify simulate proxy to expose prometheus metrics
  .prometheus.dev.yml
  BUILD.md
  controller/script/simulate-proxy/main.go
  docker-compose.yml
Labels: review, review/ready

#583 Update Prometheus to scrape data and control plane
  cli/cmd/inject.go
  cli/cmd/testdata/inject_emojivoto_deployment.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_controller_name.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_false.golden.yml
  cli/cmd/testdata/inject_gettest_deployment.good.golden.yml
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
Labels: area/telemetry, review, review/ready

#601 Fix double comma in outbound metrics
  proxy/src/telemetry/metrics/prometheus.rs
  proxy/tests/telemetry.rs
Labels: area/proxy, area/telemetry, review

#448 Add the proxy pod owner as a Prometheus label
  cli/cmd/inject.go
  cli/cmd/testdata/inject_emojivoto_deployment.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_controller_name.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_false.golden.yml
  cli/cmd/testdata/inject_gettest_deployment.good.golden.yml
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
Labels: review

#591 Introduce Conduit Health dashboard
  cli/cmd/install.go
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/health.go
  cli/install/template.go
Labels: area/telemetry, review

#589 Add request_duration_ms metric and increment request_total on request end
  proxy/src/bind.rs
  proxy/src/outbound.rs
  proxy/src/telemetry/event.rs
  proxy/src/telemetry/metrics/mod.rs
  proxy/src/telemetry/metrics/prometheus.rs
  proxy/src/telemetry/sensor/http.rs
  proxy/src/telemetry/sensor/mod.rs
  proxy/src/transparency/client.rs
  proxy/tests/telemetry.rs
Labels: area/proxy, area/telemetry, review

#605 Move injected data from env var to k8s labels
  cli/cmd/inject.go
  cli/cmd/testdata/inject_emojivoto_deployment.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_controller_name.golden.yml
  cli/cmd/testdata/inject_emojivoto_deployment_hostNetwork_false.golden.yml
  cli/cmd/testdata/inject_gettest_deployment.good.golden.yml
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
  doc/prometheus.md
  doc/proxy-metrics.md
  pkg/k8s/labels.go
  proxy/src/telemetry/metrics/prometheus.rs
Labels: area/cli, area/telemetry, review

#609 Update docker-compose environment to match prod
  .prometheus.dev.yml
  controller/script/simulate-proxy/main.go
  docker-compose.yml
  grafana/dev.datasources.yaml
  grafana/dev.grafana.ini
Labels: area/telemetry, review

#611 Remove references to `cli` images
  bin/docker-images
  bin/docker-pull
  bin/docker-push
  bin/docker-retag-all
Labels: priority/P0, review

#614 Skip flaky tests for #613
  proxy/tests/telemetry.rs
Labels: review

#617 Proxy: Clarify destination test support code queue handling
  proxy/tests/support/controller.rs
Labels: review

#626 Actually skip flaky tests on CI
  .travis.yml
  proxy/Dockerfile
Labels: area/build, area/proxy, area/test, review

#628 Add process_start_time_seconds Prometheus metric
  proxy/src/ctx/mod.rs
  proxy/src/telemetry/control.rs
  proxy/src/telemetry/metrics/prometheus.rs
Labels: area/proxy, area/telemetry, review

#564 Add the NoEndpoints message to the Destinations API
  controller/destination/server.go
  controller/gen/common/common.pb.go
  controller/gen/controller/telemetry/telemetry.pb.go
  controller/gen/proxy/destination/destination.pb.go
  controller/gen/proxy/tap/tap.pb.go
  controller/gen/proxy/telemetry/telemetry.pb.go
  controller/gen/public/api.pb.go
  controller/k8s/endpoints.go
  controller/script/destination-client/main.go
  proto/proxy/destination/destination.proto
  proxy/src/control/discovery.rs
Labels: review

#603 All counters in proxy telemetry wrap on overflows
  proxy/src/telemetry/metrics/latency.rs
  proxy/src/telemetry/metrics/mod.rs
  proxy/src/telemetry/metrics/prometheus.rs
Labels: area/proxy, area/telemetry, review

#633 Clean up Prometheus labels scraped from proxy
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_output.golden
  cli/install/template.go
  controller/script/simulate-proxy/main.go
  doc/prometheus.md
  doc/proxy-metrics.md
Labels: area/telemetry, review

#608 Add tests/utils/scripts for running integration tests
  BUILD.md
  Gopkg.lock
  TEST.md
  bin/test-cleanup
  bin/test-run
  cli/Dockerfile-bin
  controller/Dockerfile
  proxy-init/Dockerfile
  proxy-init/integration_test/run_tests.sh
  test/egress/egress_test.go
  test/egress/testdata/proxy.yaml
  test/get/get_test.go
  test/get/testdata/not_to_be_injected_application.yaml
  test/get/testdata/to_be_injected_application.yaml
  test/install_test.go
  test/testdata/check.golden
  test/testdata/smoke_test.yaml
  testutil/doc.go
  testutil/kubernetes_helper.go
  testutil/stream.go
  testutil/test_helper.go
  web/Dockerfile
Labels: review

#635 Higher velocity metrics from simulate-proxy
  .prometheus.dev.yml
  controller/script/simulate-proxy/main.go
  docker-compose.yml
Labels: area/telemetry, area/test, review

#639 Add response classification to proxy metrics
  doc/proxy-metrics.md
  proxy/src/telemetry/metrics/prometheus.rs
  proxy/tests/telemetry.rs
Labels: area/proxy, area/telemetry, review

#630 remove toggle sorting functionality from TableComponent
  web/app/js/components/BaseTable.jsx
  web/app/js/components/MetricsTable.jsx
Labels: review

#612 Improve CLI docker caching
  cli/Dockerfile-bin
Labels: area/build, area/cli, review

#646 fix grafana CrashLoopBackoff on image 5.0.3
  cli/cmd/install.go
  cli/cmd/testdata/install_default.golden
  docker-compose.yml
Labels: area/telemetry

#637 Update Grafana dashboards to use new proxy metrics
  cli/cmd/testdata/install_default.golden
  cli/install/deployment.go
  cli/install/health.go
  cli/install/viz.go
Labels: area/telemetry

#632 Proxy: Completely replace current set of destinations on reconnect
  proxy/src/control/discovery.rs
  proxy/tests/discovery.rs
  proxy/tests/support/controller.rs
Labels: review

#645 Refactor destination service and add tests in preparation to add information about labels
  controller/destination/destination_resolver.go
  controller/destination/dns.go
  controller/destination/echo_ip_resolver.go
  controller/destination/echo_ip_resolver_test.go
  controller/destination/k8s_resolver.go
  controller/destination/k8s_resolver_test.go
  controller/destination/server.go
  controller/destination/server_test.go
  controller/destination/test_helper.go
  controller/k8s/endpoints.go
  controller/k8s/test_helper.go
Labels: area/controller, priority/P0, review, review/ready

#656 Fix mock controller in proxy tests after adding labels to destinations
  proxy/tests/support/controller.rs
Labels: area/proxy, area/telemetry, area/test, review

#653 Modify simulate-proxy to be more pod-centric
  .prometheus.dev.yml
  controller/k8s/replicasets.go
  controller/script/simulate-proxy/main.go
  docker-compose.yml
Labels: area/telemetry, review
