Repository linkerd/linkerd2, pull requests merged in 2020-03, with the labels that each got.

#4114 Use SHAs instead of tags when referring to GH Actions libs
  .github/workflows/cloud_integration.yml
  .github/workflows/kind_integration.yml
  .github/workflows/release.yml
  .github/workflows/static_checks.yml
  .github/workflows/unit_tests.yml
Labels: area/build, area/security

#4117 Fix `bin/fetch-proxy` on Linux
  bin/fetch-proxy
Labels: area/build

#4118 Introduce `bin/shellcheck`, add to ci
  .github/workflows/static_checks.yml
  TEST.md
  bin/shellcheck
Labels: area/build, area/test

#4119 Fix namespace-scoped Grafana links
  web/app/js/components/GrafanaLink.jsx
  web/app/js/components/GrafanaLink.test.jsx
Labels: area/web, bug

#4129 CI: Adjustments to the release job
  .github/workflows/release.yml
  bin/_release.sh
  bin/create-release-tag
Labels: area/build

#4137 Fix shellcheck warning
  bin/_release.sh
Labels: area/build

#4144 Improve release tag script
  bin/create-release-tag
Labels: area/build

#4159 Upload artifacts for all PRs
  .github/workflows/kind_integration.yml
Labels: area/build

#4171 Add retries to certain `linkerd check` checks
  pkg/healthcheck/healthcheck.go
Labels: area/cli

#4173 Update linkerd/stern to fix go.mod
  Dockerfile-proxy
  cli/Dockerfile-bin
  cni-plugin/Dockerfile
  controller/Dockerfile
  go.mod
  go.sum
  web/Dockerfile
Labels: area/build

#4181 Upgrade golangci-lint to v1.23.8
  .golangci.yml
  bin/lint
  cli/cmd/inject.go
  cli/cmd/uninject.go
  pkg/k8s/fake.go
Labels: area/build

#4180 Fix error when injecting Cronjobs that have no metadata
  charts/patch/templates/patch.json
  cli/cmd/inject_test.go
  cli/cmd/testdata/inject_emojivoto_cronjob.golden.yml
  cli/cmd/testdata/inject_emojivoto_cronjob.input.yml
  cli/cmd/testdata/inject_emojivoto_cronjob.report
  cli/cmd/testdata/inject_emojivoto_cronjob.report.verbose
  cli/cmd/testdata/inject_emojivoto_cronjob_nometa.golden.yml
  cli/cmd/testdata/inject_emojivoto_cronjob_nometa.input.yml
  pkg/inject/inject.go
Labels: area/inject, bug

#4193 Add missing PSP for linkerd-smi-metrics
  charts/linkerd2/templates/psp.yaml
  cli/cmd/testdata/install_config.golden
  cli/cmd/testdata/install_controlplane_tracing_output.golden
  cli/cmd/testdata/install_custom_registry.golden
  cli/cmd/testdata/install_default.golden
  cli/cmd/testdata/install_ha_output.golden
  cli/cmd/testdata/install_ha_with_overrides_output.golden
  cli/cmd/testdata/install_heartbeat_disabled_output.golden
  cli/cmd/testdata/install_helm_output.golden
  cli/cmd/testdata/install_helm_output_ha.golden
  cli/cmd/testdata/install_no_init_container.golden
  cli/cmd/testdata/install_output.golden
  cli/cmd/testdata/install_proxy_ignores.golden
  cli/cmd/testdata/install_restricted_dashboard.golden
  cli/cmd/testdata/install_tracing.golden
  cli/cmd/testdata/upgrade_default.golden
  cli/cmd/testdata/upgrade_external_issuer.golden
  cli/cmd/testdata/upgrade_ha.golden
  cli/cmd/testdata/upgrade_ha_config.golden
  cli/cmd/testdata/upgrade_overwrite_issuer.golden
  cli/cmd/testdata/upgrade_overwrite_trust_anchors-external-issuer.golden
  cli/cmd/testdata/upgrade_overwrite_trust_anchors.golden
Labels: area/install, bug

#4201 New test for checking SA lists are synced
  pkg/healthcheck/healthcheck.go
  test/serviceaccounts/serviceaccounts_test.go
Labels: area/test

#4212 Extract common logic in scripts and CI to load images into KinD
  .github/workflows/kind_integration.yml
  .github/workflows/release.yml
  bin/install-pr
  bin/kind-load
Labels: area/build
