Repository linkerd/linkerd2, pull requests merged in 2020-02, with the labels that each got.

#4001 Allow CI to run concurrent builds in master
  .github/workflows/workflow.yml
  .gitignore
  bin/_gcp.sh
Labels: area/build

#4018 Address external_issuer_test.go flakiness
  test/externalissuer/external_issuer_test.go
Labels: area/test

#3965 Fix flakey TestGetProfiles
  controller/api/destination/server_test.go
Labels: area/test

#4020 Integration test flakiness: endpoint version mismatch warning
  test/install_test.go
Labels: area/build, area/test

#4058 bin/helm-build automatically updates version in values.yaml
  BUILD.md
  bin/helm-build
  charts/linkerd2-cni/values.yaml
  charts/linkerd2/values.yaml
  pkg/charts/charts.go
  pkg/charts/cni/values.go
  pkg/charts/linkerd2/values.go
Labels: area/build

#4074 CI: Upgrades the gcloud action to fix GKE clusters teardown issue
  .github/workflows/cloud_integration.yml
Labels: area/build, area/test

#4077 Edge-20.2.2 release notes
  CHANGES.md
Labels: area/build

#4086 Update gcloud configs for the chart_deploy job
  .github/workflows/cloud_integration.yml
Labels: area/build

#4087 Update gcloud configs for the chart_deploy job - Part 2
  .github/workflows/cloud_integration.yml
Labels: area/build

#4088 Reuse bin/helm-build in Helm integration tests
  bin/_test-run.sh
  bin/helm-build
Labels: area/test

#4080 Fixed shellcheck warnings on bin/helm-build
  bin/helm-build
Labels: area/build

#4091 Add script to create release tag
  bin/create-release-tag
Labels: area/build

#4084 Exclude changes on markup files to trigger CI runs in master
  .github/workflows/cloud_integration.yml
  .github/workflows/kind_integration.yml
  .github/workflows/static_checks.yml
  .github/workflows/unit_tests.yml
Labels: area/build

#4094 New CI job to automatically generate the Github release
  .github/workflows/cloud_integration.yml
  .github/workflows/release.yml
Labels: area/build

#4106 Added last release job to verify version was published in the website
  .github/workflows/release.yml
Labels: area/build
